import type { CompletionItem } from "./types";

export const VPYTHON_OBJECTS: CompletionItem[] = [
  {
    label: "sphere",
    type: "function",
    info: "Create a sphere",
    detail: "(pos, radius, color, ...)",
  },
  { label: "box", type: "function", info: "Create a box", detail: "(pos, size, color, ...)" },
  {
    label: "cylinder",
    type: "function",
    info: "Create a cylinder",
    detail: "(pos, axis, radius, color, ...)",
  },
  {
    label: "cone",
    type: "function",
    info: "Create a cone",
    detail: "(pos, axis, radius, color, ...)",
  },
  { label: "arrow", type: "function", info: "Create an arrow", detail: "(pos, axis, color, ...)" },
  {
    label: "helix",
    type: "function",
    info: "Create a helix/spring",
    detail: "(pos, axis, radius, coils, ...)",
  },
  {
    label: "ring",
    type: "function",
    info: "Create a ring",
    detail: "(pos, axis, radius, thickness, ...)",
  },
  {
    label: "pyramid",
    type: "function",
    info: "Create a pyramid",
    detail: "(pos, size, color, ...)",
  },
  {
    label: "ellipsoid",
    type: "function",
    info: "Create an ellipsoid",
    detail: "(pos, size, color, ...)",
  },
  { label: "curve", type: "function", info: "Create a curve", detail: "(pos, color, ...)" },
  { label: "points", type: "function", info: "Create points", detail: "(pos, color, ...)" },
  { label: "label", type: "function", info: "Create a text label", detail: "(pos, text, ...)" },
  { label: "text", type: "function", info: "Create 3D text", detail: "(text, pos, color, ...)" },
  { label: "compound", type: "function", info: "Combine objects", detail: "(objects)" },
  {
    label: "vertex",
    type: "function",
    info: "Create a vertex",
    detail: "(pos, normal, color, ...)",
  },
  { label: "triangle", type: "function", info: "Create a triangle", detail: "(v0, v1, v2)" },
  { label: "quad", type: "function", info: "Create a quad", detail: "(v0, v1, v2, v3)" },
  {
    label: "extrusion",
    type: "function",
    info: "Create an extrusion",
    detail: "(path, shape, ...)",
  },
  { label: "paths", type: "class", info: "Path utilities" },
  { label: "shapes", type: "class", info: "Shape utilities" },
];

export const VPYTHON_FUNCTIONS: CompletionItem[] = [
  { label: "vector", type: "function", info: "Create a 3D vector", detail: "(x, y, z)" },
  { label: "vec", type: "function", info: "Create a 3D vector (alias)", detail: "(x, y, z)" },
  { label: "rate", type: "function", info: "Control animation speed", detail: "(fps)" },
  { label: "sleep", type: "function", info: "Pause execution", detail: "(seconds)" },
  { label: "mag", type: "function", info: "Vector magnitude", detail: "(vector)" },
  { label: "mag2", type: "function", info: "Vector magnitude squared", detail: "(vector)" },
  { label: "norm", type: "function", info: "Normalized vector", detail: "(vector)" },
  { label: "hat", type: "function", info: "Unit vector (alias)", detail: "(vector)" },
  { label: "cross", type: "function", info: "Cross product", detail: "(v1, v2)" },
  { label: "dot", type: "function", info: "Dot product", detail: "(v1, v2)" },
  { label: "diff_angle", type: "function", info: "Angle between vectors", detail: "(v1, v2)" },
  { label: "rotate", type: "function", info: "Rotate a vector", detail: "(vector, angle, axis)" },
  {
    label: "adj_color",
    type: "function",
    info: "Adjust color brightness",
    detail: "(color, factor)",
  },
  { label: "color_to_rgb", type: "function", info: "Convert color to RGB", detail: "(color)" },
  { label: "rgb_to_color", type: "function", info: "Convert RGB to color", detail: "(r, g, b)" },
  { label: "arange", type: "function", info: "Create range array", detail: "(start, stop, step)" },
  {
    label: "linspace",
    type: "function",
    info: "Create linear space",
    detail: "(start, stop, num)",
  },
  { label: "gcurve", type: "function", info: "Graph curve", detail: "(color, ...)" },
  { label: "gdots", type: "function", info: "Graph dots", detail: "(color, ...)" },
  { label: "gvbars", type: "function", info: "Graph vertical bars", detail: "(color, ...)" },
  { label: "ghbars", type: "function", info: "Graph horizontal bars", detail: "(color, ...)" },
  {
    label: "graph",
    type: "function",
    info: "Create a graph",
    detail: "(title, xtitle, ytitle, ...)",
  },
  { label: "attach_trail", type: "function", info: "Attach trail to object", detail: "(obj, ...)" },
  {
    label: "attach_arrow",
    type: "function",
    info: "Attach arrow to object",
    detail: "(obj, attr, ...)",
  },
  { label: "attach_light", type: "function", info: "Attach light to object", detail: "(obj, ...)" },
];

export const VPYTHON_MATH: CompletionItem[] = [
  { label: "sin", type: "function", info: "Sine", detail: "(x)" },
  { label: "cos", type: "function", info: "Cosine", detail: "(x)" },
  { label: "tan", type: "function", info: "Tangent", detail: "(x)" },
  { label: "asin", type: "function", info: "Arc sine", detail: "(x)" },
  { label: "acos", type: "function", info: "Arc cosine", detail: "(x)" },
  { label: "atan", type: "function", info: "Arc tangent", detail: "(x)" },
  { label: "atan2", type: "function", info: "Arc tangent of y/x", detail: "(y, x)" },
  { label: "sqrt", type: "function", info: "Square root", detail: "(x)" },
  { label: "exp", type: "function", info: "Exponential", detail: "(x)" },
  { label: "log", type: "function", info: "Natural logarithm", detail: "(x)" },
  { label: "log10", type: "function", info: "Base-10 logarithm", detail: "(x)" },
  { label: "pow", type: "function", info: "Power", detail: "(x, y)" },
  { label: "abs", type: "function", info: "Absolute value", detail: "(x)" },
  { label: "ceil", type: "function", info: "Ceiling", detail: "(x)" },
  { label: "floor", type: "function", info: "Floor", detail: "(x)" },
  { label: "round", type: "function", info: "Round", detail: "(x, digits)" },
  { label: "max", type: "function", info: "Maximum", detail: "(...)" },
  { label: "min", type: "function", info: "Minimum", detail: "(...)" },
  { label: "radians", type: "function", info: "Degrees to radians", detail: "(deg)" },
  { label: "degrees", type: "function", info: "Radians to degrees", detail: "(rad)" },
  { label: "pi", type: "constant", info: "Pi (3.14159...)" },
  { label: "random", type: "function", info: "Random number 0-1", detail: "()" },
];

export const VPYTHON_COLORS: CompletionItem[] = [
  { label: "color.red", type: "constant", info: "Red color" },
  { label: "color.green", type: "constant", info: "Green color" },
  { label: "color.blue", type: "constant", info: "Blue color" },
  { label: "color.yellow", type: "constant", info: "Yellow color" },
  { label: "color.orange", type: "constant", info: "Orange color" },
  { label: "color.cyan", type: "constant", info: "Cyan color" },
  { label: "color.magenta", type: "constant", info: "Magenta color" },
  { label: "color.purple", type: "constant", info: "Purple color" },
  { label: "color.white", type: "constant", info: "White color" },
  { label: "color.black", type: "constant", info: "Black color" },
  { label: "color.gray", type: "function", info: "Gray color", detail: "(brightness)" },
  { label: "color.hsv_to_rgb", type: "function", info: "HSV to RGB", detail: "(hsv)" },
  { label: "color.rgb_to_hsv", type: "function", info: "RGB to HSV", detail: "(rgb)" },
];

export const VPYTHON_PROPERTIES: CompletionItem[] = [
  { label: "pos", type: "property", info: "Position vector" },
  { label: "axis", type: "property", info: "Axis vector" },
  { label: "up", type: "property", info: "Up vector" },
  { label: "size", type: "property", info: "Size vector" },
  { label: "color", type: "property", info: "Color" },
  { label: "radius", type: "property", info: "Radius" },
  { label: "length", type: "property", info: "Length" },
  { label: "height", type: "property", info: "Height" },
  { label: "width", type: "property", info: "Width" },
  { label: "thickness", type: "property", info: "Thickness" },
  { label: "opacity", type: "property", info: "Opacity (0-1)" },
  { label: "shininess", type: "property", info: "Shininess" },
  { label: "emissive", type: "property", info: "Emissive (glowing)" },
  { label: "texture", type: "property", info: "Texture" },
  { label: "visible", type: "property", info: "Visibility" },
  { label: "make_trail", type: "property", info: "Enable trail" },
  { label: "trail_type", type: "property", info: "Trail type" },
  { label: "trail_color", type: "property", info: "Trail color" },
  { label: "trail_radius", type: "property", info: "Trail radius" },
  { label: "retain", type: "property", info: "Trail points to retain" },
  { label: "interval", type: "property", info: "Trail interval" },
  { label: "velocity", type: "property", info: "Velocity (custom attr)" },
  { label: "momentum", type: "property", info: "Momentum (custom attr)" },
  { label: "mass", type: "property", info: "Mass (custom attr)" },
];

export const VPYTHON_SCENE: CompletionItem[] = [
  { label: "scene", type: "variable", info: "The default scene/canvas" },
  { label: "scene.background", type: "property", info: "Background color" },
  { label: "scene.center", type: "property", info: "Camera center" },
  { label: "scene.forward", type: "property", info: "Camera forward direction" },
  { label: "scene.up", type: "property", info: "Camera up direction" },
  { label: "scene.range", type: "property", info: "Camera distance" },
  { label: "scene.fov", type: "property", info: "Field of view" },
  { label: "scene.lights", type: "property", info: "Scene lights" },
  { label: "scene.ambient", type: "property", info: "Ambient light color" },
  { label: "scene.width", type: "property", info: "Canvas width" },
  { label: "scene.height", type: "property", info: "Canvas height" },
  { label: "scene.title", type: "property", info: "Scene title" },
  { label: "scene.caption", type: "property", info: "Scene caption" },
  { label: "scene.autoscale", type: "property", info: "Auto-scale camera" },
  { label: "scene.userzoom", type: "property", info: "Allow user zoom" },
  { label: "scene.userspin", type: "property", info: "Allow user spin" },
  { label: "scene.userpan", type: "property", info: "Allow user pan" },
  {
    label: "scene.bind",
    type: "function",
    info: "Bind event handler",
    detail: "(event, function)",
  },
  {
    label: "scene.unbind",
    type: "function",
    info: "Unbind event handler",
    detail: "(event, function)",
  },
  { label: "scene.waitfor", type: "function", info: "Wait for event", detail: "(event)" },
  { label: "scene.pause", type: "function", info: "Pause for click", detail: "(prompt)" },
  { label: "scene.capture", type: "function", info: "Capture screenshot", detail: "(filename)" },
];

export const VPYTHON_VECTORS: CompletionItem[] = [
  { label: "x", type: "property", info: "X component" },
  { label: "y", type: "property", info: "Y component" },
  { label: "z", type: "property", info: "Z component" },
  { label: "mag", type: "property", info: "Magnitude" },
  { label: "mag2", type: "property", info: "Magnitude squared" },
  { label: "hat", type: "property", info: "Unit vector" },
  { label: "norm", type: "function", info: "Normalize", detail: "()" },
  { label: "dot", type: "function", info: "Dot product", detail: "(other)" },
  { label: "cross", type: "function", info: "Cross product", detail: "(other)" },
  { label: "proj", type: "function", info: "Projection", detail: "(other)" },
  { label: "comp", type: "function", info: "Component", detail: "(other)" },
  { label: "diff_angle", type: "function", info: "Angle to other", detail: "(other)" },
  { label: "rotate", type: "function", info: "Rotate vector", detail: "(angle, axis)" },
];

export const PYTHON_KEYWORDS: CompletionItem[] = [
  { label: "True", type: "keyword" },
  { label: "False", type: "keyword" },
  { label: "None", type: "keyword" },
  { label: "and", type: "keyword" },
  { label: "or", type: "keyword" },
  { label: "not", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "elif", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "pass", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "def", type: "keyword" },
  { label: "class", type: "keyword" },
  { label: "import", type: "keyword" },
  { label: "from", type: "keyword" },
  { label: "as", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "except", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "raise", type: "keyword" },
  { label: "with", type: "keyword" },
  { label: "lambda", type: "keyword" },
  { label: "yield", type: "keyword" },
  { label: "global", type: "keyword" },
  { label: "nonlocal", type: "keyword" },
  { label: "assert", type: "keyword" },
  { label: "del", type: "keyword" },
  { label: "in", type: "keyword" },
  { label: "is", type: "keyword" },
  { label: "print", type: "function", info: "Print to console", detail: "(...)" },
  { label: "len", type: "function", info: "Length", detail: "(obj)" },
  { label: "range", type: "function", info: "Range iterator", detail: "(start, stop, step)" },
  { label: "list", type: "function", info: "Create list", detail: "(iterable)" },
  { label: "dict", type: "function", info: "Create dictionary", detail: "(...)" },
  { label: "tuple", type: "function", info: "Create tuple", detail: "(iterable)" },
  { label: "set", type: "function", info: "Create set", detail: "(iterable)" },
  { label: "str", type: "function", info: "Convert to string", detail: "(obj)" },
  { label: "int", type: "function", info: "Convert to integer", detail: "(obj)" },
  { label: "float", type: "function", info: "Convert to float", detail: "(obj)" },
  { label: "bool", type: "function", info: "Convert to boolean", detail: "(obj)" },
  { label: "type", type: "function", info: "Get type", detail: "(obj)" },
  { label: "isinstance", type: "function", info: "Check instance", detail: "(obj, class)" },
  { label: "enumerate", type: "function", info: "Enumerate iterator", detail: "(iterable)" },
  { label: "zip", type: "function", info: "Zip iterables", detail: "(...)" },
  { label: "map", type: "function", info: "Map function", detail: "(func, iterable)" },
  { label: "filter", type: "function", info: "Filter iterable", detail: "(func, iterable)" },
  { label: "sorted", type: "function", info: "Sort iterable", detail: "(iterable)" },
  { label: "reversed", type: "function", info: "Reverse iterable", detail: "(iterable)" },
  { label: "sum", type: "function", info: "Sum of iterable", detail: "(iterable)" },
  { label: "any", type: "function", info: "Any true", detail: "(iterable)" },
  { label: "all", type: "function", info: "All true", detail: "(iterable)" },
];

/** All top-level completions (used when not after a dot). */
export const ALL_COMPLETIONS: CompletionItem[] = [
  ...VPYTHON_OBJECTS,
  ...VPYTHON_FUNCTIONS,
  ...VPYTHON_MATH,
  ...VPYTHON_COLORS,
  ...VPYTHON_SCENE,
  ...PYTHON_KEYWORDS,
];

/** Property completions (used after a dot). */
export const PROPERTY_COMPLETIONS: CompletionItem[] = [...VPYTHON_PROPERTIES, ...VPYTHON_VECTORS];
